apiVersion: v1
kind: Service
metadata:
  name: {{ include "vespa.fullname" . }}-configserver
  labels:
    {{- include "vespa.labels" . | nindent 4 }}
    app: configserver
spec:
  ports:
    - port: 19071
      targetPort: 19071
      name: configserver
  selector:
    app: configserver
  clusterIP: None

