apiVersion: v1
kind: Service
metadata:
  name: {{ include "vespa.fullname" . }}-container
  labels:
    {{- include "vespa.labels" . | nindent 4 }}
    app: container
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      name: http
  selector:
    app: container

