apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vespa.fullname" . }}
  labels:
    {{- include "vespa.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "vespa.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "vespa.name" . }}
    spec:
      containers:
        - name: vespa
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
              name: http
          command: ["/bin/sh", "-c"]
          args:
            - |
              /opt/vespa/bin/vespa-start-services && \
              tail -f /dev/null
          env:
            - name: VESPA_CONFIGSERVERS
              value: "localhost"

