# templates/service.yaml

apiVersion: v1
kind: Service
metadata:
  name: {{ include "vespa.fullname" . }}
  labels:
    {{- include "vespa.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "vespa.name" . }}

